<?php 

return [
    'app_name' => 'Models',

    'Models' => 'Models',
    'Edit' => 'Edit',
    'Fields' => 'Fields',
    'Groups' => 'Groups',
    'Settings' => 'Settings',
    'Methods' => 'Methods',
    'Field groups' => 'Field groups',
    'Dependencies' => 'Dependencies',
    'New model' => 'New model',
    'Models does not exist' => 'Models does not exist',
    'Create' => 'Create',
    'Update' => 'Update',
    'Name' => 'Name',
    'Display name' => 'Display name',
    'Display name plural' => 'Display name plural',
    'The model is created' => 'The model is created',
    'The model is updated' => 'The model is updated',
    'The model field is created' => 'The model field is created',
    'Access' => 'Access',
    'This model has not useful fields' => 'This model has not useful fields',
    'Delete' => 'Delete',
    'Are you sure' => 'Are you sure',
    'Are you sure you want to delete the model' => 'Are you sure you want to delete the model',
    'Delete model' => 'Delete model',

    'settings' => [
        'Show in admin tree' => 'Show in admin tree',
        'Nodes ordering' => 'Nodes ordering',
        'Dynamic model' => 'Dynamic model',
        'The model settings is updated' => 'The model settings is updated',
        'Use response cache' => 'Use response cache',
        'Generate new slug automaticly' => 'Generate new slug automaticly',
        'Max nodes count' => 'Max nodes count',
        'Ordering in admin panel and in then scope ordered()' => 'Ordering in admin panel and in then scope ordered()',
        'Name of class stored in App\Models' => 'Name of class stored in App\Models',
        'Here you can determine how many nodes of this model can be created in the admin panel' => 'Here you can determine how many nodes of this model can be created in the admin panel',
        'Nodes of this model will be displayed in the tree' => 'Nodes of this model will be displayed in the tree',
        'There are restrictions on the level of nesting: only two levels are displayed' => 'There are restrictions on the level of nesting: only two levels are displayed',
        'Responses of this model will be cached and returned without processing by the controllers' => 'Responses of this model will be cached and returned without processing by the controllers',
        'Only GET requests are processed' => 'Only GET requests are processed',
        'Please note: if your page contains forms with CSRF protection - do not use caching' => 'Please note: if your page contains forms with CSRF protection - do not use caching',
        'After node updating, new slug will be generated automaticly, based on the name field' => 'After node updating, new slug will be generated automaticly, based on the name field',
        'Do not use for static partitions such as "news list", "contacts," etc' => 'Do not use for static partitions such as "news list", "contacts," etc',
        'Node icon' => 'Node icon',
        'The icon will be displayed in the tree' => 'The icon will be displayed in the tree',
        'Is searchable' => 'Is searchable',
        'The model will be available for search in the admin panel' => 'The model will be available for search in the admin panel',
        'The search requires a Name field' => 'The search requires a Name field',
        'Require to fill fields for SEO' => 'Require to fill fields for SEO',
        'In the nodes, in which no title and descripton fields are filled, a warning will be displayed' => 'In the nodes, in which no title and descripton fields are filled, a warning will be displayed',
        'This option requires the following fields' => 'This option requires the following fields',
        'Redirect to node after creation' => 'Redirect to node after creation',
        'After the section is created, the user will be redirected to the edit instead of the list' => 'After the section is created, the user will be redirected to the edit instead of the list',
    ],

    'methods' => [
        'GET' => 'GET',
        'POST' => 'POST',
        'PATCH' => 'PATCH',
        'DELETE' => 'DELETE',
        'The model methods are updated' => 'The model methods are updated',
        'Update' => 'Update',
        'You can configure 4 default methods for sections of this model' => 'You can configure 4 default methods for sections of this model',
        'Edit' => 'Edit',
        'The model method is used' => 'The model method is used',

        'errors' => [
            'String must contain @' => 'String must contain @',
            'Сontroller does not exist' => 'Сontroller does not exist',
            'Method does not exist' => 'Method does not exist',
        ],
    ],

    'fields' => [
        'Hint' => 'Hint',
        'Display name' => 'Display name',
        'Name' => 'Name',
        'Settings' => 'Settings',
        'Position' => 'Position',
        'Delete' => 'Delete',
        'Type' => 'Type',
        'Field type' => 'Field type',
        'The field is updated' => 'The field is updated',
        'Create' => 'Create',
        'Update' => 'Update',
        'Are you sure' => 'Are you sure',
        'Yes' => 'Yes',
        'No' => 'No',
        'Without group' => 'Without group',
        'Group' => 'Group',
        'Edit' => 'Edit',
        'New field' => 'New field',
        'Access' => 'Access',
        'The field is removed' => 'The field is removed',
        'Is common for all languages' => 'Is common for all languages',
        'Is visible in nodes list' => 'Is visible in nodes list',
        'Are you sure you want to delete the field' => 'Are you sure you want to delete the field',
        'Delete field' => 'Delete field',
        'Close' => 'Close',
        'Templates' => 'Templates',
        'Other fields' => 'Other fields',
        'Select file' => 'Select file',
        'Missing model name' => 'Missing model name',
        'The name of database field' => 'The name of database field',
        'Is visible in admin panel' => 'Is visible in admin panel',
        'Appears under the field in the admin panel' => 'Appears under the field in the admin panel',
        'Common field for all languages: the control will only be displayed in the primary language tab, but the value will be duplicated in all other languages' => 'Common field for all languages: the control will only be displayed in the primary language tab, but the value will be duplicated in all other languages',
        'The value of the field will be displayed in the list of nodes' => 'The value of the field will be displayed in the list of nodes',
        'Open' => 'Open',
        'WARNING' => 'WARNING',
        'The required fields for the SEO are not completed' => 'The required fields for the SEO are not completed',
        'Max' => 'Max',

        'settings' => [
            'control' => 'Control',
            'size' => 'Size',
            'image_size' => 'Image size',
            'custom_validation_rules' => 'Custom validation rules',
            'Update' => 'Update',
            'The model field settings are updated' => 'The model field settings are updated',
            'Column length' => 'Column length',
            'For fields, like decimal, you can use two numbers, separated by a comma' => 'For fields, like decimal, you can use two numbers, separated by a comma',
            'related_model_name' => 'Related model name',
            'related_parent_node_id' => 'Related parent node id',
        ],

        'access' => [
            'Update' => 'Update',
            'Group name' => 'Group name',
            'Read' => 'Read',
            'Edit' => 'Edit',
            'Access is updated' => 'Access is updated',
        ],

        'errors' => [
            'The model should contain a field "name"' => 'The model should contain a field "name"',
            'Can not change name because another model uses it' => 'Can not change name because another model uses it',
        ],
    ],

    'dependencies' => [
        'The model dependency is created' => 'The model dependency is created',
        'The model dependency is deleted' => 'The model dependency is deleted',
        'Available models' => 'Available models',
        'Depended models' => 'Depended models',
        'Add dependent models' => 'Add dependent models',
        'The sections of the models on the right column can be created under the sections of this model' => 'The sections of the models on the right column can be created under the sections of this model',
        'Position' => 'Position',
    ],

    'groups' => [
        'New group' => 'New group',
        'Name' => 'Name',
        'Position' => 'Position',
        'Delete' => 'Delete',
        'Create' => 'Create',
        'Update' => 'Update',
        'Are you sure' => 'Are you sure',
        'The group is updated' => 'The group is updated',
        'The group is deleted' => 'The group is deleted',
    ],

    'access' => [
        'Group name' => 'Group name',
        'Read' => 'Read',
        'Edit' => 'Edit',
        'Update' => 'Update',
        'Access is updated' => 'Access is updated',
    ],
];
