<?php 

return [
    'Models' => 'Models',
    'Edit' => 'Edit',
    'Fields' => 'Fields',
    'Groups' => 'Groups',
    'Settings' => 'Settings',
    'Methods' => 'Methods',
    'Field groups' => 'Field groups',
    'Dependencies' => 'Dependencies',
    'New model' => 'New model',
    'Models does not exist' => 'Models does not exist',
    'Create' => 'Create',
    'Update' => 'Update',
    'Name' => 'Name',
    'Display name' => 'Display name',
    'Display name plural' => 'Display name plural',
    'The model is created' => 'The model is created',
    'The model is updated' => 'The model is updated',
    'Access' => 'Access',

    'settings' => [
        'Show in admin tree' => 'Show in admin tree',
        'Nodes ordering' => 'Nodes ordering',
        'Dynamic model' => 'Dynamic model',
        'The model settings is updated' => 'The model settings is updated',
        'Use response cache' => 'Use response cache',
    ],

    'methods' => [
        'GET' => 'GET',
        'POST' => 'POST',
        'PATCH' => 'PATCH',
        'DELETE' => 'DELETE',
        'The model methods are updated' => 'The model methods are updated',
        'Update' => 'Update',
        'You can configure 4 default methods for sections of this model' => 'You can configure 4 default methods for sections of this model',
    ],

    'fields' => [
        'Hint' => 'Hint',
        'Display name' => 'Display name',
        'Name' => 'Name',
        'Settings' => 'Settings',
        'Position' => 'Position',
        'Delete' => 'Delete',
        'Type' => 'Type',
        'Field type' => 'Field type',
        'The field is updated' => 'The field is updated',
        'Create' => 'Create',
        'Update' => 'Update',
        'Are you sure' => 'Are you sure',
        'Yes' => 'Yes',
        'No' => 'No',
        'Without group' => 'Without group',
        'Group' => 'Group',
        'Edit' => 'Edit',
        'New field' => 'New field',
        'Access' => 'Access',
        'The field is removed' => 'The field is removed',
        'Is common for all languages' => 'Is common for all languages',
        'Is visible in nodes list' => 'Is visible in nodes list',
        'Are you sure you want to delete the field' => 'Are you sure you want to delete the field',
        'Delete field' => 'Delete field',
        'Close' => 'Close',

        'settings' => [
            'control' => 'Control',
            'size' => 'Size',
            'image_size' => 'Image size',
            'custom_validation_rules' => 'Custom validation rules',
            'Update' => 'Update',
            'The model field settings are updated' => 'The model field settings are updated',
            'Column length' => 'Column length',
            'For fields, like decimal, you can use two numbers, separated by a comma' => 'For fields, like decimal, you can use two numbers, separated by a comma',
            'related_model_name' => 'Related model name',
            'related_parent_node_id' => 'Related parent node id',
        ],

        'access' => [
            'Update' => 'Update',
            'Group name' => 'Group name',
            'Read' => 'Read',
            'Edit' => 'Edit',
            'Access is updated' => 'Access is updated',
        ],
    ],

    'dependencies' => [
        'The model dependency is created' => 'The model dependency is created',
        'The model dependency is deleted' => 'The model dependency is deleted',
        'Available models' => 'Available models',
        'Depended models' => 'Depended models',
        'Add dependent models' => 'Add dependent models',
        'The sections of the models on the right column can be created under the sections of this model' => 'The sections of the models on the right column can be created under the sections of this model',
        'Position' => 'Position',
    ],

    'groups' => [
        'New group' => 'New group',
        'Name' => 'Name',
        'Position' => 'Position',
        'Delete' => 'Delete',
        'Create' => 'Create',
        'Update' => 'Update',
        'Are you sure' => 'Are you sure',
        'The group is updated' => 'The group is updated',
        'The group is deleted' => 'The group is deleted',
    ],

    'access' => [
        'Group name' => 'Group name',
        'Read' => 'Read',
        'Edit' => 'Edit',
        'Update' => 'Update',
        'Access is updated' => 'Access is updated',
    ],
];
